### PR TITLE
fix dot helper

### PR DESCRIPTION
**Pull request by gBokiau**

### CODE REVIEW

**Comment by kylekatarnls** [comment]
Hi, sorry, but this is not relevant. As you can see, this do not pass the unit tests.

We expect js-phpize to behave like JS code would:
`foo.bar` does not execute any method and if you want call `bar` on `foo` you can easily do it with `foo.bar()`.

This is needed since methods can have arguments: `date.formatLocalized('%A %d %B %Y')`

So it would be a very bad idea to execute automatically methods on objects. This would break very conveniant features.

If there is something you tried to fix, please let me know.

**Comment by gBokiau** [comment]
You're right. I ran into trouble with the dot helper in different scenarios, this was what seemed to work for me.  I hope to come around to posting test cases of things that didn't work as expected. Hasty brain dump for the time being:

For context, I personally prefer `__call` over `__get` for template data, which clarifies that the property at hand isn't meant to be writable (I thus use `__get` solely for control properties)  — but I agree that it would be unexpected behavior for `foo.bar` to map to `$foo->bar()`.  However I'm not sure that it would hurt either, at least as a last resort. (as opposed to current situation, see last paragraph below)

I also had the impression `foo.bar()` wasn't _always_ working through `$foo->__call('bar')`  - I need to double check and pinpoint the culprit if and when it didn't.

Mostely though, the `array($foo, 'bar')` that is returned as a last resort eluded me, and I was under the impression from the set of conditions that `$foo->$bar()` was the intendend outcome. I'm curious then in which scenario `array($foo, 'bar')` would be a correct translation for a javascript dot ?

In any case, it doesn't seem right that `foo.bar` would return `array($foo, 'bar')` when an object doesn't have a `bar` value, but has either of a `bar()` or a `__call()` method. 

Does that make sense?

**Comment by kylekatarnls** [comment]
In fact, when you append arguments such as `("args")` after **foo.bar**, `array($foo, 'bar')` is passed to `call_user_func` like this: `call_user_func(array($foo, 'bar'), "args")`, so you get exactly `$foo->bar("args")` result and there is no conflict with `__call`.

But it seems you use an anti-pattern for `__call` and `__get`. A method is an action (it should start with a verb) while a property should be a concrete value/object (it should be a noun). In the same way, `__call` rely to method/action, `__get` rely to property.

So good uses would look like:
```js
car.wheels
car.getWheels()
car.starter
car.start()
```

The following are a certain sign of breaking-pattern:
```js
car.wheels()
car.getWheels
car.starter()
car.start
```

I can consider provide some help tools. But this change is certainly not a fix, it will break existing codes. Merge your pull request means that pug-php users that can have some code like this in my first example:
```js
date.formatLocalized('%A %d %B %Y')
```
will get an exception on updating dependencies and will no longer be able to pass arguments to methods as they would be able to do in pugjs.

You have to find the root cause of your trouble, what is your object, what is your template. If I well understand you want to call `__call("bar")` on `$foo`, the PHP call for that would be `$foo->bar()`, si the equivalent JS would be `foo.bar()`. If this is right, the following is working on unit tests: https://github.com/pug-php/js-phpize/blob/master/tests/dotHelper.php#L135

And I see no valid reason to provide other syntax than `foo.bar()` for this call.

**Comment by gBokiau** [comment]
Thanks for the write-up. 

You're absolutely correct about the anti-pattern. Apologies for the digression.

Some further digging has led me to precise, legitimate issues though:
- Things go haywire when the object doesn't have a `__isset` method and does have a `__get` method. The dot helper then returns `null` instead of the value that a native `$foo->bar` would return.
- If it does have both `__get` and `__isset`, and also has `_call`, `foo.nonExistentProperty` returns `array($foo, 'nonExistentProperty')` instead of `null`
- If it only has `_call`, `foo.nonExistentProperty` returns `array($foo, 'nonExistentProperty')` instead of throwing an error

Would unit tests help?

**Comment by gBokiau** [comment]
See #15

**Comment by kylekatarnls** [comment]
In fact, it would be easy if we would just support objects, but we also support arrays.
`foo.bar` can be `$foo["bar"]` or `$foo->bar` or both since both arrays and object can have magic access:
http://php.net/manual/en/arrayaccess.offsetexists.php
And you also have the magic ArrayObject:
http://php.net/manual/en/class.arrayobject.php

So our choice is:
- it should works with simple objects and simple arrays with a smooth detection.
- for magic array/object, we must rely on `__isset` and `offsetExists`. If we cannot know in a trustable way if a property exists we cannot know if we have to fallback to array offset or to method. So we expect the developer that use magic method to know what he's doing and well implement the complete interfaces (set/get/isset/unset).
- the last fallback is method/callable

And we cannot really re-order that list since callable can be method, magic method or a closure, so in other priority order, we will lost ability to fallback to all possibilities and will break existing templates.

So my recommendation for this point is:
- there's no harm in implementing `__isset` on your magic objects or `offsetExists` on your magic arrays, it's even a best practice.
- if you depend on a library that have `__get` / `offsetGet` without `__isset` / `offsetExists`, explain them they should implement it to handle codes like:
```php
if (isset($object->property)) {
}

if (isset($array['offset'])) {
}
```

**Pull request closed without merging**
